### ISSUE TITLE
No mobile tutorial

### ISSUE THREAD

**Issue by AAAAAAAAAAAAAAAAAAAAAAAAA-boop** [Minesraft2/Blooket-Cheats#497]
Add a mobile tutorial :D

**Comment by Minesraft2** [comment]
i dont know how to do it on mobile

**Comment by Realswitzer** [comment]
Doing it on mobile seems to involve either syncing browsers (requires Google Chrome, Firefox, Opera, and Safari although that also requires user to have a mac os product and sign in there), or using "Bookmarks Easy Import" on Android as suggested on [Google Chrome forums](https://support.google.com/chrome/thread/3498184/how-do-i-import-my-chrome-bookmarks-to-my-android-device?hl=en)
![image](https://user-images.githubusercontent.com/39711351/221710575-a5bf2477-6214-439c-b02e-039198b82063.png)
and after clicking accept:
![image](https://user-images.githubusercontent.com/39711351/221710730-d45e1a69-d34d-42e4-ad29-32a68dfa80f2.png)

While Chrome and Firefox are both common, it is pretty dependent on having done it on a computer and using the appropriate browser sync feature to get it on mobile.

**Comment by SharkyMantisGD** [comment]
So on Apple devices you can't get it the UI?

**Comment by Realswitzer** [comment]
It seems possible to get the bookmarks on there, though for getting it on mobile it requires a Mac, and I’m unable to test if bookmarklets (specifically the one for this repo) would work on mobile. Bookmarklets on mobile definitely exist [Digital Inspiration](https://www.labnol.org/software/iphone-ipad-bookmarklets/18969/) but at the bottom it says “Note: You may have noticed that a couple of really good bookmarklets … are missing here and that’s because they do not work with the mobile Safari browser.”

**Comment by rbcoder117** [comment]
I am doing it on Mobile:
You need chrome for mobile here is photo
![71EB6DFE-B5DD-4E7C-BEF6-7C6D25E1FE94](https://user-images.githubusercontent.com/91441703/222786574-6b8f3321-7b13-40c9-8eb0-9fc3b78a746e.jpeg)

**Comment by rbcoder117** [comment]
Problem is you dont get UI

**Comment by rbcoder117** [comment]
It’s too long it crashes

**Comment by fgrtgtrgtrgrt** [comment]
did you use the mobilegui.js?

**Comment by HiMyNameIsZeno** [comment]
rbcoder117 is right. This is one of the methods that I use for mobile. However another method that might help is a mobile console (ex. Eruda). This is very easy but can cause a bit of lag in game. When you get to the website, copy the line of code and put it into a bookmarklet. Then while in a blooket game, tap on the bookmarklet, then a GUI button will show up. Tap it, then paste the mobile gui code into the console, and hit execute. Now keep in mind, this might take time for the console to load because of the blooket game that is being played. This link will take you to Eruda: https://github.com/liriliri/eruda

**Comment by Minesraft2** [comment]
We have actually no idea how to do it on mobile, try just googling a method to run javascript on a webpage
