### ISSUE TITLE
Make Open Chromas

### ISSUE THREAD

**Issue by r3a1ty** [Minesraft2/Blooket-Cheats#501]
### Gamemode

gobial

### Function

It does open chromas for packs that you choose

**Comment by Greenlio** [comment]
@VillainsRule4000 idec how stupid the comment is; call someone retarded in a issues again and I'm gonna block you from responding to them lol

**Comment by Realswitzer** [comment]
Impossible due to opening packs being managed on Blooket’s end, this is the same reason why it’s impossible to add infinite tokens, bypass the daily limit, hit level 100 in a day, etc.
Hopefully I’m not missing anything here and it’s more apparent why we can’t do it.
If they were possible, they would have been made.
