### ISSUE TITLE
Cheat GUI without bookmarks

### ISSUE THREAD

**Issue by epicgameenjoyer** [Minesraft2/Blooket-Cheats#508]
### Script

gui

### Problem

So, my school has disabled bookmarks and I tried to do this through URL but it's not working. Anyone know how to make it work through URL?

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

I got it to work on bookmark.

**Comment by Minesraft2** [comment]
Try dragging a cheat from https://minesraft2.github.io/Blooket-Cheats to your bookmarks bar, if that doesn't work idk what to do.

**Comment by epicgameenjoyer** [comment]
Alright, I'll try that.

**Comment by epicgameenjoyer** [comment]
Update: i tried dragging the link over and it said: This site can’t be reached www.google.com unexpectedly closed the connection.

**Comment by Minesraft2** [comment]
you gotta go to the website, then drag one of the icons with a purple label to the bookmarks bar

**Comment by epicgameenjoyer** [comment]
didnt work

**Comment by Korozin** [comment]
The only methods besides Console and URL / Bookmarklet execution that I can think of for this user would be User-Scripts, but if their school is considering blocking Javascript execution of any kind, then that kind of method won't even be accessible to them either.

There are of course other methods such as I-Frame injection, forcing Web-Side rendering, or setting up a Web-Worker- but that's starting to leave the scope of possibility for what I think the OP is capable of, much less even in their ability to try. So this seems like more or less a dead end because of lack of methods to even start execution.  🤷‍♀️

**Comment by epicgameenjoyer** [comment]
sombody figured out how to do it. so i guess its cased closed.

**Comment by epicgameenjoyer** [comment]
and JavaScript: works

**Comment by epicgameenjoyer** [comment]
> > The only methods besides Console and URL / Bookmarklet execution that I can think of for this user would be User-Scripts, but if their school is considering blocking Javascript execution of any kind, then that kind of method won't even be accessible to them either.
> 
> Evidently any school competent enough to block Bookmarklets is gonna block Tampermonkey.
> 
> > There are of course other methods such as I-Frame injection, forcing Web-Side rendering, or setting up a Web-Worker- but that's starting to leave the scope of possibility for what I think the OP is capable of, much less even in their ability to try. So this seems like more or less a dead end because of lack of methods to even start execution. 🤷‍♀️
> 
> Yes. Evidently, forcing these methods on the chromebook has consequences. However, the Blooket Utility [currently unmaintained] was created for a "if all has been tried" idea.
> 
> There's always [sh1mmer](https://sh1mmer.me).

Sombody figured out how to do it, and typing JavaScript: in the URL works. Our school did block inspect element though.
