### ISSUE TITLE
IDEA: Change blooks during game

### ISSUE THREAD

**Issue by Staraner** [Minesraft2/Blooket-Cheats#786]
### Gamemode

All gamemodes

### Function

When I joined the game late, I can't change my blook so I am stuck with a STUPID COMMON BLOOK so the hack let's me to change my blook instead of looking like a poor idiot

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by noimno** [comment]
nice idea the same thing happens to me and I hate when that happens..

**Comment by JavascriptCoder5400** [comment]
I have some code that might be able to fix this, but you would have to type in the SPECIFIC NAME of the blook you would like. You also have to be careful about which blook you chose, because if you chose a blook that someone else has, the game will bug out horribly.   Another bug with the code that I am using is that when you interact with another player, the live game controller switches you back to your original blook. I am working on some code to fix that bug. I also have some other code you might be interested in, but here is the code (this has to be put in a bookmarklet, otherwise, I don't know how to do it): javascript:(async()=>{var t=document.createElement("iframe");document.body.append(t);t.style.display="none";window.prompt=t.contentWindow.bind(window);var e=prompt("Which blook would you like? (bugged)");var o=Object.values(document.querySelector("#app > div > div"))[1].children[0]._owner.stateNode;o.props.liveGameController.setVal({path:'c/'.concat(o.props.client.name),val:{b:"Ice Slime",g:o.state.gold}});})();

**Comment by JavascriptCoder5400** [comment]
I almost made all game modes: javascript:(async()=>{var t=document.createElement("iframe");document.body.append(t);t.style.display="none";window.prompt=t.contentWindow.prompt.bind(window);var e=prompt("Which blook would you like? (bugged)");var o=Object.values(document.querySelector("#app > div > div"))[1].children[0]._owner.stateNode;o.props.client.blook=e;o.props.liveGameController.setVal({path:'c/'.concat(o.props.client.name),val:(location.pathname==='/play/gold'?{b:e,g:o.state.gold}:location.pathname==='/play/hack'?{b:e,p:o.state.password,cr:o.state.crypto}:location.pathname==='/play/fishing'?{b:e,w:o.state.weight}:location.pathname==='/play/defense2'?{b:e,d:o.state.totalDmg}:location.pathname==='/play/dino'?{b:e,f:o.state.fossils,ic:o.state.isCheating}:{})});})();

**Comment by Minesraft2** [comment]
global > changeBlookIngame.js
