### ISSUE TITLE
IDEA: Free Blooket Plus

### ISSUE THREAD

**Issue by MrGamer-FS** [Minesraft2/Blooket-Cheats#848]
### Gamemode

Global

### Function

Gives you free Blooket+ so you can do more things.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by EnderC00kiez** [comment]
Like what? There's already Unlock Plus Gamemodes.

**Comment by MasonTheGreat123** [comment]
> Like what? There's already Unlock Plus Gamemodes.

the whole plus not the gamemodes

**Comment by Realswitzer** [comment]
> All Starter Features
> Enhanced Game Reports

May be server sided since they host the games on their servers

> Early Event Access

unsure though probably server sided

> Question Set Folders

Not sure if possible now though it was at least possible in the past, feel free to correct.

> Student Bonus Tokens

At least for a time I had this effect for free, plus it only works if you host.

> Copy & Duplicate Sets

If I had to guess, if the folder is/was possible then this may also be possible. Granted, I have not checked though I guess if you make a script to duplicate a set, you could probably pull it off without Plus.

> Up to 300 Players

Like the bonus tokens, this also happened to me though still not sure if it happens now. Again, due to them hosting the games on their servers, I think they would implement checks to see if the host has Plus.

I do not know the inner workings of Blooket so this is going off of what I suspect, though take this with a grain of salt.

**Comment by OGBlooketCheater** [comment]
> Like what? There's already Unlock Plus Gamemodes.

that doesnt work

**Comment by Educational-hacker** [comment]
300 players should work if i am not wrong.

**Comment by MrGamer-FS** [comment]
I mean to make your account plus without paying for plus. Could even be use once then have to insert code again if page is reloaded or smth like that

**Comment by Co1t0n** [comment]
the only way to get plus is paying for it . maybe pay the 5 bucks

**Comment by GITHUBTRASHACCOUNT** [comment]
tampermonkey script could repeatly excute code for blooklet +

**Comment by Minesraft2** [comment]
Only thing you can't get from other scripts is folder and set features, both of which are managed server-side
