### ISSUE TITLE
IDEA: antiremoveal.js  (so you cant be removed by the mod for cheating)

### ISSUE THREAD

**Issue by FBIsurvalincevan15** [Minesraft2/Blooket-Cheats#916]
### Gamemode

all

### Function

Prevents you from being removed by the mod.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Parker0909** [comment]
Yes Very Good Idea

**Comment by pazza2234** [comment]
Some things I would like to bring up is that the hoast acts like the server right? or, if not I know if the host leaves the game ends. so if the host kicks the host would also stop sending packets to the client and making it impossable right? I just want to bring these things up. But a get around could be having no name because to hilight then remove a person you nead to hover over the text. and the teachers are probaly not going to use inspect or somthing.

**Comment by Realswitzer** [comment]
still unsure if host acts as the server. while i have tested and confirmed that when the tab hosting the game is closed, the game ends, though i would expect that the host interacts with the server, and the server is what all of the clients talk to given that blooket is a website and i don't think they would make it p2p or have the host be the server.
i didn't use wireshark to try finding what packets are sent to determine who it's sent to, so im unable to figure that out -- using chrome devtools on network only showed loading images on chest unlock, not any communication with a server/host.
could be completely wrong so don't take this as fact.

> But a get around could be having no name

![image](https://github.com/Minesraft2/Blooket-Cheats/assets/39711351/61aad135-b701-4e11-915a-65ee1f68c032)
![image](https://github.com/Minesraft2/Blooket-Cheats/assets/39711351/869afac2-632c-4a19-8b5c-92839c24ab8e)
from just deleting the name div element, the surrounding box (or divs) is still present, plus having no name would still probably not work due to it preventing you from having a blank name

**Comment by BOIhelv** [comment]
Another way could be when you are kicked, you automatically rejoin the game and will set you back to where you were with the normal hacks

**Comment by Educational-hacker** [comment]
> still unsure if host acts as the server. while i have tested and confirmed that when the tab hosting the game is closed, the game ends, though i would expect that the host interacts with the server, and the server is what all of the clients talk to given that blooket is a website and i don't think they would make it p2p or have the host be the server. i didn't use wireshark to try finding what packets are sent to determine who it's sent to, so im unable to figure that out -- using chrome devtools on network only showed loading images on chest unlock, not any communication with a server/host. could be completely wrong so don't take this as fact.
> 
> > But a get around could be having no name
> 
> ![image](https://user-images.githubusercontent.com/39711351/241356638-61aad135-b701-4e11-915a-65ee1f68c032.png) ![image](https://user-images.githubusercontent.com/39711351/241356662-869afac2-632c-4a19-8b5c-92839c24ab8e.png) from just deleting the name div element, the surrounding box (or divs) is still present, plus having no name would still probably not work due to it preventing you from having a blank name

Bro, if ur on chromebook, u can use unicode+3164 to get blank name

**Comment by Minesraft2** [comment]
Can't prevent kicking
